image: docker:git
services:
- docker:dind

stages:
- deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  only:
    - main
  stage: deploy
  image:
    name: python:latest
  script:
  - python3 -m pip install -U sphinx
  - python3 -m pip install --extra-index-url https://gitlab.com/api/v4/groups/70683489/-/packages/pypi/simple .
  - cd docs && make html
  artifacts:
    paths:
      - docs/_build/html
  publish: docs/_build/html

pypi-publish:
  only:
    - main
  stage: deploy
  image:
    name: python:latest
  script:
    - pip install build twine
    - python -m build
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*


