image: docker:git
services:
- docker:dind

stages:
- deploy

variables:
  API_IMAGE_NAME: $CI_REGISTRY_IMAGE/api
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  artifacts:
    paths:
    - doc/_build/html
  only:
  - main

pypi-publish:
  only:
    - main
  stage: deploy
  image:
    name: python:latest
  script:
    - pip install build twine
    - python -m build
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*


