general:
  stored_token_directory: /tmp/srcnet/user

apis:
  authn-api:
    url: https://authn.srcnet.skao.int/api/v1
  data-management-api:
    url: https://data-management.srcnet.skao.int/api/v1
  permissions-api:
    url: https://permissions.srcnet.skao.int/api/v1
  site-capabilities-api:
    url: https://site-capabilities.srcnet.skao.int/api/v1

data-management:
  clients:
    https:
      package_name: ska_src_clients.client
      module_name: data_management
      class_name: WebDAVClient3
    davs:
      package_name: ska_src_clients.client
      module_name: data_management
      class_name: WebDAVClient3